<?php

namespace furbo\museumplusforcraftcms\elements\db;
use \craft\elements\db\ElementQuery;
use craft\db\Query;
use craft\db\Table;
use craft\helpers\Db;

class MuseumPlusVocabularyQuery extends ElementQuery
{
    public $type;
    public $collectionId;

    public function collectionId($value)
    {
        $this->collectionId = $value;

        return $this;
    }

    public function type($value)
    {
        $this->type = $value;

        return $this;
    }

    protected function beforePrepare(): bool
    {
        // join in the items table
        $this->joinElementTable('museumplus_vocabulary');

        // select the collection id column
        $this->query->select([
            'museumplus_vocabulary.collectionId',
            'museumplus_vocabulary.data',
            'museumplus_vocabulary.type',
        ]);

        if ($this->collectionId) {
            $this->subQuery->andWhere(Db::parseParam('museumplus_vocabulary.collectionId', $this->collectionId));
        }

        if ($this->type) {
            $this->subQuery->andWhere(Db::parseParam('museumplus_vocabulary.type', $this->type));
        }

        return parent::beforePrepare(); // TODO: Change the autogenerated stub
    }
}