<?php
/**
 * MuseumPlus for CraftCMS plugin for Craft CMS 3.x
 *
 * Allows to import MuseumsPlus Collection data to Craft CMS and publish data. Additioanl Web Specific Data can be added to the imported data.
 *
 * @link      https://furbo.ch
 * @copyright Copyright (c) 2022 Furbo GmbH
 */

namespace furbo\museumplusforcraftcms\console\controllers;

use craft\elements\Asset;
use craft\helpers\Assets;
use craft\helpers\FileHelper;
use craft\models\VolumeFolder;
use craft\helpers\App;

use craft\queue\jobs\ResaveElements;
use craft\queue\jobs\UpdateSearchIndex;
use furbo\museumplusforcraftcms\elements\MuseumPlusPerson;
use furbo\museumplusforcraftcms\elements\MuseumPlusVocabulary;
use furbo\museumplusforcraftcms\MuseumPlusForCraftCms;
use furbo\museumplusforcraftcms\elements\MuseumPlusItem;
use furbo\museumplusforcraftcms\records\ObjectGroupRecord;
use furbo\museumplusforcraftcms\records\OwnershipRecord;
use furbo\museumplusforcraftcms\records\LiteratureRecord;
use furbo\museumplusforcraftcms\events\ItemUpdatedFromMuseumPlusEvent;

use craft\queue\Queue;
use furbo\museumplusforcraftcms\jobs\UpdateItemJob;
use furbo\museumplusforcraftcms\jobs\DeleteRemovedItemsJob;
use furbo\museumplusforcraftcms\jobs\UpdateItemParentChildRelationsJob;

use Craft;
use furbo\museumplusforcraftcms\records\MuseumPlusItemRecord;
use yii\console\Controller;
use yii\console\ExitCode;
use yii\helpers\Console;

/**
 * Collection Command
 *
 * The first line of this class docblock is displayed as the description
 * of the Console Command in ./craft help
 *
 * Craft can be invoked via commandline console by using the `./craft` command
 * from the project root.
 *
 * Console Commands are just controllers that are invoked to handle console
 * actions. The segment routing is plugin-name/controller-name/action-name
 *
 * The actionIndex() method is what is executed if no sub-commands are supplied, e.g.:
 *
 * ./craft museum-plus-for-craft-cms/collection
 *
 * Actions must be in 'kebab-case' so actionDoSomething() maps to 'do-something',
 * and would be invoked via:
 *
 * ./craft museum-plus-for-craft-cms/collection/do-something
 *
 * @author    Furbo GmbH
 * @package   MuseumPlusForCraftCms
 * @since     1.0.0
 */
class CollectionController extends Controller
{
    /**
     * @var bool|null if true - script will download all data.
     */
    public $forceAll;

    /**
     * @var int|null if set, script will downoad only this item.
     */
    public $collectionItemId;

    /**
     * @var bool|null if true - script will not download attachments.
     */
    public $ignoreAttachments;

    /**
     * @var bool|null if true - script will not download multimedia.
     */
    public $ignoreMultimedia;

    /**
     * @var bool|null if true - script will not download literature.
     */
    public $ignoreLiterature;

    /**
     * @var int startId - skip all items with id before this
     */
    public $startId;
    public $personId;

    // Private Properties
    private $start;
    private $settings;
    private $museumPlus;
    public $assets;


    // Public Methods
    // =========================================================================

    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->settings = MuseumPlusForCraftCms::$plugin->getSettings();
        $this->museumPlus = MuseumPlusForCraftCms::$plugin->museumPlus;
        $this->assets = Craft::$app->getAssets();
    }

    public function beforeAction($action)
    {
        App::maxPowerCaptain();
        $this->start = microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $end = microtime(true);
        $time = $end - $this->start;
        $time = round($time/60, 2);
        echo PHP_EOL;
        echo "Time: " . $time . " min" . PHP_EOL;
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    public function actionUpdateItem()
    {
        if (empty($this->collectionItemId)) {
            echo 'Missing param: collectionItemId' . PHP_EOL;
            return false;
        }
        $queue = Craft::$app->queue;
        $jobId = $queue->push(new UpdateItemJob([
            'collectionId' => $this->collectionItemId,
        ]));

        echo "Queued update for MuseumPlusItem {$this->collectionItemId}.\n";
        
    }

    public function actionUpdateItems()
    {
        //$this->forceAll = true;

        echo 'Downloading list of object groups'.PHP_EOL;
        $this->downloadObjectGroups();
        echo 'Download finished'.PHP_EOL;
        echo 'Updating Items'.PHP_EOL;
        $objectIds = [];

        $startUpdating = true;
        if (!empty($this->startId)) {
            $startUpdating = false;
        }
        $queue = Craft::$app->queue;
        foreach ($this->settings['objectGroups'] as $objectGroupId) {
            echo 'getObjectsByObjectGroup START'.PHP_EOL;
            $objects = $this->museumPlus->getObjectsByObjectGroup($objectGroupId, ['__id', '__lastModifiedUser', '__lastModified']);
            echo 'getObjectsByObjectGroup END'.PHP_EOL;
            foreach ($objects as $o) {
                $objectIds[$o->id] = $o->id;
                if ($startUpdating) {
                    //check if item exists and if last mod is before last mod in mplus
                    $objectLastModified = new \DateTime($o->__lastModified);
                    $item = MuseumPlusItem::find()
                        ->where(['collectionId' => $o->id])
                        ->one();
                    //$queue = Craft::$app->queue;
                    if (!$item) {
                        $jobId = $queue->push(new UpdateItemJob([
                            'description' => 'Creating item (id: '.$o->id.')',
                            'collectionId' => $o->id,
                            'ignoreAttachments' => $this->ignoreAttachments,
                            'ignoreMultimedia' => $this->ignoreMultimedia,
                            'ignoreLiterature' => $this->ignoreLiterature,
                        ]));
                        echo 'Creating item (id: '.$o->id.')'.PHP_EOL;
                    } else if ($this->forceAll || $item->dateUpdated < $objectLastModified) {
                        $jobId = $queue->push(new UpdateItemJob([
                            'description' => 'Updating item (id: '.$o->id.')',
                            'collectionId' => $o->id,
                            'ignoreAttachments' => $this->ignoreAttachments,
                            'ignoreMultimedia' => $this->ignoreMultimedia,
                            'ignoreLiterature' => $this->ignoreLiterature,
                        ]));
                        // TODO careful: triggerUpdateEvent should be false in this case
                        echo 'Updating item (id: '.$o->id.')'.PHP_EOL;
                    } else {
                        echo 'Skipping Item (id: '.$o->id.')'.PHP_EOL;
                    }
                } else {
                    $startUpdating = $o->id == $this->startId;
                    echo 'skip item '.$o->id.PHP_EOL;
                }
            }
        }

        $this->actionDeleteRemovedItems();
        
        return true;
    }


    public function actionDeleteRemovedItems()
    {
        $queue = Craft::$app->queue;
        echo 'Deleting removed items - job sent to queue'.PHP_EOL;
        $jobId = $queue->push(new DeleteRemovedItemsJob([
            'description' => 'Deleting removed items',
        ]));
        
        return true;
    }

    public function options($actionID)
    {
        $options = parent::options($actionID);
        $options[] = 'forceAll';
        $options[] = 'collectionItemId';
        $options[] = 'ignoreAttachments';
        $options[] = 'ignoreMultimedia';
        $options[] = 'ignoreLiterature';
        $options[] = 'startId';
        $options[] = 'personId';
        return $options;
    }


    public function actionRemoveAttachments()
    {
        $itemIds = MuseumPlusItem::find()->ids();
        foreach($itemIds as $itemId) {
            $item = MuseumPlusItem::find()
                ->id($itemId)
                ->one();
            if($item->assetId) {
                $asset = Asset::find()->id($item->assetId)->one();
                if ($asset) {
                    $success = Craft::$app->elements->deleteElement($asset);
                    if ($success) {
                        echo "[OK] Id:" . $item->id . " AssetID " . $item->assetId . PHP_EOL;
                    } else {
                        echo "[ERROR] Id:" . $item->id . " AssetID " . $item->assetId . PHP_EOL;
                    }
                }
            }
        }
        return true;
    }

    public function actionUpdatePeople()
    {
        $numberOfPeopleNotUpdated = 0;
        $people = MuseumPlusPerson::find()->all();
        foreach($people as $person) {
            $data = $this->museumPlus->getPerson($person->collectionId);
            if($data)
            {
                $this->createOrUpdatePerson($data);
            } else {
                $numberOfPeopleNotUpdated++;
                echo "Person with Id:" . $person->id . " and collectionId " . $person->collectionId .' was not updated: should probably be removed'. PHP_EOL;
            }
        }
        echo 'Number of people not updated that should probably be removed: '.$numberOfPeopleNotUpdated . PHP_EOL;
        return true;
    }

    public function actionUpdatePerson()
    {
        // ./craft museum-plus-for-craft-cms/collection/update-person --personId=4002
        $data = $this->museumPlus->getPerson($this->personId);
        if($data) {
            $this->createOrUpdatePerson($data);
        }
        return true;
    }

    private function createOrUpdatePerson($data)
    {
        $collectionId = $data->id;

        $person = MuseumPlusPerson::find()
            ->where(['collectionId' => $collectionId])
            ->one();

        if (empty($person)) {
            //create new
            $person = new MuseumPlusPerson();
            $person->collectionId = $collectionId;

            $success = Craft::$app->elements->saveElement($person, false);
        }
        //update
        $person->data = json_encode($data);
        if (!empty($data->PerNameTxt))
            $person->title = $data->PerNameTxt;
        else if (!empty($data->PerNameTxt))
            $person->title = $data->PerPersonTxt;
        else if (!empty($data->PerNameVrt))
            $person->title = $data->PerNameVrt;
        else
            $person->title = 'Unknown';

        $moduleRefs = $person->getDataAttribute('moduleReferences');
        if (!$this->ignoreMultimedia && isset($moduleRefs['PerMultimediaRef'])) {
            //$this->setProgress($this->queue, 0.4, "Updating item multimedia objects");
            $assetIds = [];
            $refs = $moduleRefs['PerMultimediaRef']['items'];
            //$this->sortArray($refs, 'SortLnu');
            foreach ($refs as $mm) {
                $assetId = $this->createPersonMultimediaFromId($mm['id'], $collectionId);
                if ($assetId) {
                    $assetIds[] = $assetId;
                    /*
                    if ($this->showDetailedLog) {
                        $this->logger->info("Asset created: AssetID: " . $assetId);
                    }
                    */
                }
            }
            if (count($assetIds)) {
                /*
                if ($this->showDetailedLog) {
                    $this->logger->info("At least one asset");
                }
                */

                $person->syncPersonMultimediaRelations($assetIds);
                /*
                if ($this->showDetailedLog) {
                    $this->logger->info("syncMultimediaRelations() executed");
                }
                */


                //echo "Multimedia assets for Item Id: " . $item->id . " Asset IDs: " . implode(",", $assetIds) . PHP_EOL;
            }
        }

        $success = $person->save();
        return $person;
    }


    private function createPersonMultimediaFromId($id, $personId = null)
    {
        $attachment = $this->museumPlus->getMultimediaById($id);
        $folderId = $this->settings['attachmentVolumeId'];
        $folder = $this->assets->findFolder(['id' => $folderId]);
        $parentFolder = $this->createFolder("People");
        $itemFolder = $this->createFolder($personId, $parentFolder->id, $parentFolder->path);
        if ($attachment) {
            // TODO: should we filter by file type?
            $asset = $this->createAsset($id, $attachment, $itemFolder);
            if ($asset) {
                return $asset->id;
            }
            /*
            $fileTypes = $this->settings['attachmentFileTypes'];
            if (!empty($fileTypes)) {
                // only allow file types defined in plugin settings.
                $pattern = '/\.(' . str_replace(', ', '|', $fileTypes) . ')$/i';
                if (preg_match($pattern, $attachment)) {
                    $asset = $this->createAsset($id, $attachment, $itemFolder);
                    if ($asset) {
                        return $asset->id;
                    }
                }
            } else {
                // allow any file type
                $asset = $this->createAsset($id, $attachment, $itemFolder);
                if ($asset) {
                    return $asset->id;
                }
            }
            */
        }
        return false;
    }

    public function actionUpdateSearchIndex()
    {
        $itemIds = MuseumPlusItem::find()->ids();
        foreach($itemIds as $itemId) {
            Craft::$app->getQueue()->push(new UpdateSearchIndex([
                'elementType' => MuseumPlusItem::class,
                'elementId' => $itemId,
            ]));
        }
    }

    private function downloadObjectGroups() {
        $objectGroupIds = $this->settings['objectGroups'];
        $objectGroupsData = $this->museumPlus->getObjectGroups();
        foreach ($objectGroupsData as $ogd) {
            if (in_array($ogd->id, $objectGroupIds)) {
                $this->createOrUpdateObjectGroup($ogd);
            }
        }

        $existingObjectGroups = ObjectGroupRecord::find()->all();
        foreach ($existingObjectGroups as $objectGroup) {
            if (!in_array($objectGroup->collectionId, $objectGroupIds)) {
                $success = $objectGroup->delete();
                //echo 'x';
            }
        }

        return true;
    }

    private function createOrUpdateObjectGroup($data) {
        $collectionId = $data->id;

        $objectGroup = ObjectGroupRecord::find()
            ->where(['collectionId' => $collectionId])
            ->one();

        if (empty($objectGroup)) {
            //create new
            $objectGroup = new ObjectGroupRecord();
            $objectGroup->id = 0;
            $objectGroup->collectionId = $collectionId;
            $objectGroup->title = $data->OgrNameTxt;
        } else {
            //update
            $objectGroup->title = $data->OgrNameTxt;
        }
        $objectGroup->data = json_encode($data);
        $success = $objectGroup->save();
        return $objectGroup;
    }

    public function actionOptimizeSearchIndex()
    {
        Craft::$app->db->createCommand("OPTIMIZE TABLE searchindex")->execute();
    }

    public function actionTriggerUpdateEvents() {
        $itemIds = MuseumPlusItem::find()->ids();
        foreach($itemIds as $itemId) {
            $item = MuseumPlusItem::find()
                ->id($itemId)
                ->one();
            $this->triggerUpdateEvent($item->collectionId, false);
            echo '.';
        }
        echo "done\n";
    }

    private function createFolder($folderName, $parentFolderId = null, $parentFolderPath = null)
    {
        $volumeId = $this->settings['attachmentVolumeId'];
        $volume = Craft::$app->volumes->getVolumeById($volumeId);
        if (!$volume) {
            Craft::error("Volume with ID {$volumeId} not found.", __METHOD__);
            return false;
        }
        // Find the root folder for this volume
        $rootFolder = Craft::$app->assets->getRootFolderByVolumeId($volumeId);
        if (!$rootFolder) {
            Craft::error("Root folder for volume ID {$volumeId} not found.", __METHOD__);
            return false;
        }

        if ($parentFolderId !== null) {
            // Check if the folder already exists
            $existingFolder = Craft::$app->assets->findFolder([
                'name' => $folderName,
                'parentId' => $parentFolderId
            ]);
            if ($existingFolder) {
                return $existingFolder;
            } else {
                $folder = new VolumeFolder();
                $folder->parentId = $parentFolderId;
                $folder->name = $folderName;
                $folder->volumeId = $volumeId;
                $folder->path = $parentFolderPath . $folderName . '/';
                $this->assets->createFolder($folder);
                return $folder;
            }
        } else {
// Check if the folder already exists
            $existingFolder = Craft::$app->assets->findFolder([
                'name' => $folderName,
                'parentId' => $rootFolder->id
            ]);
            if ($existingFolder) {
                return $existingFolder;
            } else {
                $folder = new VolumeFolder();
                $folder->parentId = $rootFolder->id;
                $folder->name = $folderName;
                $folder->volumeId = $volumeId;
                $folder->path = $folderName . '/';
                $this->assets->createFolder($folder);
                return $folder;
            }
        }

    }

    private function createAsset($id, $attachment, $parentFolder)
    {
        $basename = pathinfo($attachment, PATHINFO_FILENAME);
        $basename = FileHelper::sanitizeFilename($basename, [true, '_']);
        $extension = pathinfo($attachment, PATHINFO_EXTENSION);
        $filename = $basename . '_' . $id . '.' . $extension;
        $title = Assets::filename2Title($basename . '_' . $id);
        try {
            $asset = Asset::find()->title($title)->folderId($parentFolder->id)->one();
            if (is_null($asset)) {
                $asset = new Asset();
            }
            $asset->tempFilePath = $attachment;
            $asset->filename = $filename;
            $asset->newFolderId = $parentFolder->id;
            $asset->setVolumeId($parentFolder->volumeId);
            $asset->setScenario(Asset::SCENARIO_CREATE);
            $asset->avoidFilenameConflicts = true;

            $result = Craft::$app->getElements()->saveElement($asset);
            if ($result) {
                //echo '- File '.$id.PHP_EOL;
                return $asset;
            } else {
                return false;
            }
        } catch (\Throwable $e) {
            throw new \Exception("could not create asset: " . $e->getMessage());
        }
        return false;
    }

}
