<?php
/**
 * MuseumPlus for CraftCMS plugin for Craft CMS 3.x
 *
 * Allows to import MuseumsPlus Collection data to Craft CMS and publish data. Additioanl Web Specific Data can be added to the imported data.
 *
 * @link      https://furbo.ch
 * @copyright Copyright (c) 2022 Furbo GmbH
 */

namespace furbo\museumplusforcraftcms\console\controllers;

use craft\elements\Asset;
use craft\helpers\Assets;
use craft\models\VolumeFolder;
use furbo\museumplusforcraftcms\MuseumplusForCraftcms;
use furbo\museumplusforcraftcms\elements\MuseumplusItem;

use Craft;
use yii\console\Controller;
use yii\helpers\Console;

/**
 * Collection Command
 *
 * The first line of this class docblock is displayed as the description
 * of the Console Command in ./craft help
 *
 * Craft can be invoked via commandline console by using the `./craft` command
 * from the project root.
 *
 * Console Commands are just controllers that are invoked to handle console
 * actions. The segment routing is plugin-name/controller-name/action-name
 *
 * The actionIndex() method is what is executed if no sub-commands are supplied, e.g.:
 *
 * ./craft museum-plus-for-craft-cms/collection
 *
 * Actions must be in 'kebab-case' so actionDoSomething() maps to 'do-something',
 * and would be invoked via:
 *
 * ./craft museum-plus-for-craft-cms/collection/do-something
 *
 * @author    Furbo GmbH
 * @package   MuseumplusForCraftcms
 * @since     1.0.0
 */
class CollectionController extends Controller
{
    // Public Methods
    /**
     * @var bool|null if true - script finish will download all images.
     */
    public $forceAll;

    // Private Properties
    private $start;
    private $settings;
    private $collection;
    public $assets;


    // Public Methods
    // =========================================================================

    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->settings = MuseumplusForCraftcms::$plugin->getSettings();
        $this->collection = MuseumplusForCraftcms::$plugin->collection;
        $this->assets = Craft::$app->getAssets();
    }

    public function beforeAction($action)
    {
        $this->start = microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $end = microtime(true);
        $time = $end - $this->start;
        $time = round($time/60, 2);
        echo PHP_EOL;
        echo "Time: " . $time . " min" . PHP_EOL;
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /**
     * Handle museum-plus-for-craft-cms/collection console commands
     *
     * The first line of this method docblock is displayed as the description
     * of the Console Command in ./craft help
     *
     * @return mixed
     */
     public function actionImportAll()
     {
         $this->actionImportData();
         $this->actionImportAttachments();
         $this->actionImportMultimediaObjects();
     }

     public function actionImportData()
     {

         $objectIds = [];
         foreach ($this->settings['objectGroups'] as $objectGroupId) {
             $objects = $this->collection->getObjectsByObjectGroup($objectGroupId);
             foreach ($objects as $o) {
                 $objectIds[$o->id] = $o->id;
                 $this->createOrUpdateItem($o);
             }
         }

         $existingItems = MuseumplusItem::find()->all();
         foreach ($existingItems as $item) {
             if (!isset($objectIds[$item->collectionId])) {
                 $success = Craft::$app->elements->deleteElement($item);
                 echo 'x';
             }
         }

         return true;
     }

     public function options($actionID)
     {
         $options = parent::options($actionID);
         $options[] = 'forceAll';
         return $options;
     }

    public function actionImportAttachments()
     {
         $existingItems = MuseumplusItem::find()->all();
         $yesteday = new \DateTime();
         $yesteday->sub(new \DateInterval('PT24H'));

         foreach ($existingItems as $item) {
             $newDate = null;

             if(!$this->forceAll) {
                 $date = $this->collection->getObjectLastModified($item->collectionId);
                 try {
                     $newDate = new \DateTime($date);
                 } catch (\Exception $e) {}
             }

             if($newDate > $yesteday || $this->forceAll){
                 $assetId = $this->createAttachmentFromObjectId($item->collectionId);
                 if($assetId){
                     echo "[OK] Id: " . $item->id . " AssetID: " . $assetId . PHP_EOL;
                     $item->assetId = $assetId;
                     Craft::$app->elements->saveElement($item);
                 }else{
                     echo "[OK] Id: " . $item->id . " AssetID: NULL" . PHP_EOL;
                 }
             }
             echo ".";
         }

         return true;
     }

     public function actionRemoveAttachments()
     {
        $existingItems = MuseumplusItem::find()->all();
         foreach ($existingItems as $item) {
             if($item->assetId) {
                 $asset = Asset::find()->id($item->assetId)->one();
                 if ($asset) {
                     $success = Craft::$app->elements->deleteElement($asset);
                     if ($success) {
                         echo "[OK] Id:" . $item->id . " AssetID" . $item->assetId . PHP_EOL;
                     } else {
                         echo "[ERROR] Id:" . $item->id . " AssetID" . $item->assetId . PHP_EOL;
                     }
                 }
             }
         }
         return true;
     }

    public function actionImportMultimediaObjects()
    {
        $existingItems = MuseumplusItem::find()->all();
        $yesteday = new \DateTime();
        $yesteday->sub(new \DateInterval('PT24H'));

        foreach ($existingItems as $item) {
            $assetIds = [];
            foreach ($item->multiMediaObjects as $id => $value){
                $newDate = null;

                if(!$this->forceAll) {
                    $date = $this->collection->getMultimediaLastModified($id);
                    try {
                        $newDate = new \DateTime($date);
                    } catch (\Exception $e) {}
                }

                if($newDate > $yesteday || $this->forceAll) {
                    $assetId = $this->createMultimediaFromId($id);
                    if ($assetId) {
                        $assetIds[] = $assetId;
                    }
                }
            }
            if(count($assetIds)){
                echo "[OK] Id: " . $item->id . " AssetsIDs: " . implode(",", $assetIds) . PHP_EOL;
                $item->multiMedia = $assetIds;
                Craft::$app->elements->saveElement($item);
            }
        }
    }

    private function createAttachmentFromObjectId($id)
    {
         $folderId = $this->settings['attachmentVolumeId'];
         $folder = $this->assets->findFolder(['id' => $folderId]);
         $parentFolder = $this->createFolder("Items", $folderId);
         $attachment = $this->collection->getAttachmentByObjectId($id);

         if ($attachment) {
             $basename = pathinfo($attachment, PATHINFO_FILENAME);
             $extension = pathinfo($attachment, PATHINFO_EXTENSION);
             $filename = $basename . '_' . $id . '.' . $extension;
             try {
                 $asset = Asset::find()->filename($filename)->folderId($parentFolder->id)->one();
                 if(is_null($asset)){
                    $asset = new Asset();
                 }
                 $asset->tempFilePath = $attachment;
                 $asset->filename = $filename;
                 $asset->newFolderId = $parentFolder->id;
                 $asset->setVolumeId($parentFolder->volumeId);
                 $asset->setScenario(Asset::SCENARIO_CREATE);
                 $asset->avoidFilenameConflicts = true;

                 $result = Craft::$app->getElements()->saveElement($asset);
                 if ($result){
                     return $asset->id;
                 }else{
                     return false;
                 }
             } catch (\Throwable $e) {
                return false;
             }
         }
         return false;
    }

    private function createMultimediaFromId($id)
    {
        $folderId = $this->settings['attachmentVolumeId'];
        $folder = $this->assets->findFolder(['id' => $folderId]);
        $parentFolder = $this->createFolder("Multimedia", $folderId);
        $attachment = $this->collection->getMultimediaById($id);

        if ($attachment) {
            $basename = pathinfo($attachment, PATHINFO_FILENAME);
            $extension = pathinfo($attachment, PATHINFO_EXTENSION);
            $filename = $basename . '_' . $id . '.' . $extension;
            try {
                $asset = Asset::find()->filename($filename)->folderId($parentFolder->id)->one();
                if(is_null($asset)){
                    $asset = new Asset();
                }
                $asset->tempFilePath = $attachment;
                $asset->filename = $filename;
                $asset->newFolderId = $parentFolder->id;
                $asset->setVolumeId($parentFolder->volumeId);
                $asset->setScenario(Asset::SCENARIO_CREATE);
                $asset->avoidFilenameConflicts = true;

                $result = Craft::$app->getElements()->saveElement($asset);
                if ($result){
                    return $asset->id;
                }else{
                    return false;
                }
            } catch (\Throwable $e) {
                return false;
            }
        }
        return false;
    }

    private function createFolder($folderName, $parentFolderId)
    {
        $folder = $this->assets->findFolder(['name' => $folderName, 'parentId' => $parentFolderId]);
        if (is_null($folder)) {
            $folder = new VolumeFolder();
            $folder->parentId = $parentFolderId;
            $folder->name = $folderName;
            $folder->volumeId = $this->settings['attachmentVolumeId'];
            $folder->path = $folderName . '/';
            $this->assets->createFolder($folder);
            return $folder;
        } else {
            return $folder;
        }
    }

    private function createOrUpdateItem($object) {
        $collectionId = $object->id;

        $item = MuseumplusItem::find()
            ->where(['collectionId' => $collectionId])
            ->one();

        if (empty($item)) {
            //create new
            $item = new MuseumplusItem();
            $item->collectionId = $collectionId;
            $item->data = json_encode($object);
            $item->title = $object->ObjObjectTitleVrt;
            $success = Craft::$app->elements->saveElement($item);
        } else {
            //update
            $item->data = json_encode($object);
            if (empty($item->title)) {
                $item->title = $object->ObjObjectTitleVrt;
            }
            $success = Craft::$app->elements->saveElement($item);
        }
        echo '.';
        return true;
    }

}
